import importlib.util
import json
import logging
import sys
import types
import inspect
import asyncio
import os
import subprocess
from pathlib import Path
from typing import Optional, Any, List, Dict
from embeddr_core.services.lotus_registry import LotusRegistry
from embeddr_core.models.lotus import LotusKind, LotusCapability
from embeddr_core.models.artifact_type import ArtifactType, ArtifactTypeSpec
from embeddr.db.session import get_engine
from sqlmodel import Session
from fastapi import FastAPI, APIRouter, Depends
from embeddr_core.plugin_interface import (
    EmbeddrPlugin,
    PluginIntent,
    PluginContext,
    ConfigRendererComponent,
)
from embeddr_core.services.resource_manager import resource_manager
from embeddr.core.event_bus import SimpleEventBus, _EVENT_BUS
from embeddr.core.execution_spine import ExecutionSpine
from embeddr_core.services.config_service import resolve_plugin_config_for_plugin
from embeddr.core.plugin_context_helpers import LotusContext
from embeddr.core.config import get_data_dir

logger = logging.getLogger(__name__)

# Ensure virtual package for plugins exists
if "embeddr_plugins" not in sys.modules:
    plugin_pkg = types.ModuleType("embeddr_plugins")
    plugin_pkg.__path__ = []
    sys.modules["embeddr_plugins"] = plugin_pkg


# LOTUS
_LOTUS_REGISTRY = LotusRegistry()


def get_lotus_registry() -> LotusRegistry:
    return _LOTUS_REGISTRY


# Registry of loaded plugins
_LOADED_PLUGINS: List[EmbeddrPlugin] = []
# _EVENT_BUS is imported from event_bus.py (singleton)

# Capability registry: maps PluginIntent to list of plugin instances
_PLUGIN_CAPABILITY_REGISTRY: Dict[PluginIntent, list] = {}


def get_plugins_by_intent(intent: PluginIntent) -> List[EmbeddrPlugin]:
    """
    Return all loaded plugins that provide the given intent/capability.
    """
    return _PLUGIN_CAPABILITY_REGISTRY.get(intent, [])


def register_plugin_capabilities(plugin: EmbeddrPlugin):
    """
    Register plugin's capabilities (intents) in the global registry.
    """
    for intent in plugin.intents:
        if intent not in _PLUGIN_CAPABILITY_REGISTRY:
            _PLUGIN_CAPABILITY_REGISTRY[intent] = []
        _PLUGIN_CAPABILITY_REGISTRY[intent].append(plugin)


def get_loaded_plugins() -> List[Dict[str, Any]]:
    plugins = []
    for p in _LOADED_PLUGINS:
        panels = getattr(p, "panels", [])
        docks = getattr(p, "docks", [])
        config_renderers = getattr(p, "config_renderers", [])
        # Construct the frontend JS URL assuming standard build output.
        # Server mounts /plugins -> plugins directory.
        # Frontend expects 'url' field.

        plugin_data = {
            "id": p.name,  # Frontend typically uses 'id'
            "name": p.name,
            "version": p.version,
            "intents": [i.value for i in p.intents],
            "actions": [a.model_dump() for a in p.actions],
            "frontend_actions": [a.model_dump() for a in getattr(p, "frontend_actions", [])],
            "frontend_components": [c.model_dump() for c in getattr(p, "frontend_components", [])],
            "panels": [c.model_dump() for c in panels],
            "docks": [c.model_dump() for c in docks],
            "config_renderers": [
                c.model_dump() for c in config_renderers
                if isinstance(c, ConfigRendererComponent)
            ],
            "pages": [c.model_dump() for c in getattr(p, "pages", [])],
            "widgets": [c.model_dump() for c in getattr(p, "widgets", [])],
        }

        # Only add URL if the plugin actually has a dist (frontend build)
        source_path = getattr(p, '_source_path', None)
        if source_path and (source_path / "dist").exists():
            # Point to the UMD bundle generated by embeddr-sdk
            # Bundle name is derived from the plugin folder name (normalized)
            # We mount static assets at /plugins/{name}/static (public)
            bundle_base = source_path.name.replace("_", "-")
            bundle_name = f"{bundle_base}.umd.js"
            dist_dir = source_path / "dist"
            if not (dist_dir / bundle_name).exists():
                bundle_name = "index.umd.js"
            plugin_data["url"] = (
                f"/plugins/{p.name}/static/dist/{bundle_name}"
            )
            css_path = dist_dir / "style.css"
            if css_path.exists():
                plugin_data["css_url"] = (
                    f"/plugins/{p.name}/static/dist/style.css"
                )

        plugins.append(plugin_data)
    return plugins


def get_all_plugin_instances() -> List[EmbeddrPlugin]:
    return _LOADED_PLUGINS


def get_plugin_instance(name: str) -> Optional[EmbeddrPlugin]:
    for p in _LOADED_PLUGINS:
        if p.name == name:
            return p
    return None


def load_python_plugins(plugins_dir: Path, app: Optional[FastAPI] = None, cli_app: Any = None) -> None:
    """
    Scans the plugins directory for subdirectories containing a 'plugin.py' file.
    If found, it attempts to load the module and register it.
    Also recurses into specific folders like 'examples' and 'private_plugins'.
    """
    if not plugins_dir.exists():
        return

    logger.debug(f"Scanning for Python plugins in {plugins_dir}...")
    import typer

    def _load_disabled_plugins() -> set[str]:
        disabled: set[str] = set()
        raw = os.environ.get("EMBEDDR_DISABLED_PLUGINS", "").strip()
        if raw:
            disabled.update({item.strip()
                            for item in raw.split(",") if item.strip()})

        data_root = Path(os.environ.get("EMBEDDR_DATA_DIR") or get_data_dir())
        disabled_path = data_root / "disabled_plugins.json"
        if disabled_path.exists():
            try:
                payload = json.loads(disabled_path.read_text(encoding="utf-8"))
                items = payload.get("disabled_plugins") if isinstance(
                    payload, dict) else None
                if isinstance(items, list):
                    disabled.update({str(item).strip()
                                    for item in items if str(item).strip()})
            except Exception:
                pass
        return disabled

    disabled_plugins = _load_disabled_plugins()

    def _maybe_install_requirements(p_dir: Path) -> None:
        if str(os.environ.get("EMBEDDR_PLUGINS_AUTO_INSTALL", "")).lower() not in (
            "1",
            "true",
            "yes",
            "on",
        ):
            return

        req_file = p_dir / "requirements.txt"
        if not req_file.exists():
            return

        logger.info("[PluginLoader] Auto-installing deps for %s", p_dir.name)
        try:
            subprocess.check_call(
                ["uv", "pip", "install", "-r", str(req_file)])
            return
        except (FileNotFoundError, subprocess.CalledProcessError):
            logger.warning(
                "[PluginLoader] uv pip failed, falling back to pip for %s", p_dir.name)

        try:
            subprocess.check_call(
                [sys.executable, "-m", "pip", "install", "-r", str(req_file)])
        except subprocess.CalledProcessError as exc:
            logger.error(
                "[PluginLoader] Dependency install failed for %s: %s", p_dir.name, exc)

    def process_plugin_dir(p_dir: Path):
        if p_dir.name in disabled_plugins:
            logger.info(
                "[PluginLoader] Skipping disabled plugin %s", p_dir.name)
            return
        plugin_file = p_dir / "plugin.py"
        if not plugin_file.exists():
            return

        _maybe_install_requirements(p_dir)

        folder_name = p_dir.name  # directory name
        try:
            # --- Ensure virtual package for plugins exists ---
            if "embeddr_plugins" not in sys.modules:
                pkg = types.ModuleType("embeddr_plugins")
                pkg.__path__ = []
                sys.modules["embeddr_plugins"] = pkg

            # --- Folder-based module name (how we load from disk) ---
            folder_safe = folder_name.replace("-", "_").replace(".", "_")
            folder_module_name = f"embeddr_plugins.{folder_safe}"

            logger.debug(
                "[PluginLoader] Loading from dir=%s folder_module=%s",
                str(p_dir),
                folder_module_name,
            )

            # Load the module as a package (submodule_search_locations allows relative imports)
            spec = importlib.util.spec_from_file_location(
                folder_module_name,
                plugin_file,
                submodule_search_locations=[str(p_dir)],
            )
            if not spec or not spec.loader:
                logger.error(
                    "[PluginLoader] Spec loader missing for %s", str(plugin_file))
                return

            module = importlib.util.module_from_spec(spec)
            module.__path__ = [str(p_dir)]
            module.__package__ = folder_module_name

            # Register module under folder name BEFORE executing (relative imports rely on this)
            sys.modules[folder_module_name] = module

            # Execute plugin module
            spec.loader.exec_module(module)

            # 1) Class-based Plugin (New System)
            plugin_instance = None
            for name, obj in inspect.getmembers(module):
                if (
                    inspect.isclass(obj)
                    and issubclass(obj, EmbeddrPlugin)
                    and obj is not EmbeddrPlugin
                    and obj.__module__ == module.__name__
                ):
                    plugin_instance = obj()
                    break

            if plugin_instance:
                # Canonical module name based on the plugin's declared name
                plugin_name = plugin_instance.name
                plugin_safe = plugin_name.replace("-", "_").replace(".", "_")
                canonical_module_name = f"embeddr_plugins.{plugin_safe}"

                # --- Alias folder_module -> canonical_module ---
                # This is the key fix that makes model paths stable:
                #   embeddr_plugins.<safe(plugin_instance.name)>.models:MyModel
                if canonical_module_name != folder_module_name:
                    sys.modules[canonical_module_name] = module
                    logger.info(
                        "[PluginLoader] Aliased plugin module: %s -> %s (dir=%s)",
                        folder_module_name,
                        canonical_module_name,
                        str(p_dir),
                    )

                    # Alias common submodules if they exist under the folder module name
                    # e.g. embeddr_plugins.folder_name.models -> embeddr_plugins.plugin_name.models
                    folder_prefix = folder_module_name + "."
                    canonical_prefix = canonical_module_name + "."

                    # If the plugin (during exec_module) imported its own submodules,
                    # they will show up as sys.modules entries like:
                    #   embeddr_plugins.<folder_safe>.models
                    # We alias ALL loaded children under that prefix.
                    to_alias = [
                        m for m in list(sys.modules.keys())
                        if m.startswith(folder_prefix)
                    ]
                    for old in to_alias:
                        new = canonical_prefix + old[len(folder_prefix):]
                        if new not in sys.modules:
                            sys.modules[new] = sys.modules[old]
                            logger.debug(
                                "[PluginLoader]   Aliased submodule: %s -> %s", old, new)

                # --- Existing plugin instance check (dedupe) ---
                existing_plugin = next(
                    (p for p in _LOADED_PLUGINS if p.name == plugin_instance.name), None)
                if existing_plugin:
                    plugin_instance = existing_plugin
                    is_new_load = False
                    logger.debug(
                        "[PluginLoader] Reusing existing plugin instance: %s", plugin_instance.name)
                else:
                    _LOADED_PLUGINS.append(plugin_instance)
                    register_plugin_capabilities(plugin_instance)
                    is_new_load = True

                # --- Track source path for static files (your existing logic) ---
                new_has_dist = (p_dir / "dist").exists()
                current_path = getattr(plugin_instance, "_source_path", None)
                current_has_dist = (
                    (current_path / "dist").exists()
                    if current_path and isinstance(current_path, Path)
                    else False
                )

                if not current_path:
                    plugin_instance._source_path = p_dir
                elif new_has_dist:
                    plugin_instance._source_path = p_dir
                elif not current_has_dist:
                    plugin_instance._source_path = p_dir

                # --- Debug summary for load/aliasing ---
                if is_new_load:
                    icons = ["🐍"]
                    extras = []

                    if any(a.ui_component for a in getattr(plugin_instance, "actions", [])):
                        icons.append("⚛️")
                        extras.append("UI")
                    if PluginIntent.ZEN_PANEL in plugin_instance.intents:
                        icons.append("🧘")
                        extras.append("Zen")
                    if PluginIntent.REGISTER_API in plugin_instance.intents:
                        icons.append("🔌")
                        extras.append("API")
                    if PluginIntent.REGISTER_CLI in plugin_instance.intents:
                        icons.append("💻")
                        extras.append("CLI")

                    icon_str = " ".join(icons)
                    extra_str = f"({', '.join(extras)})" if extras else ""
                    logger.info(
                        "Loaded Plugin: %s  %s v%s %s  (folder=%s module=%s canonical=%s)",
                        icon_str,
                        plugin_instance.name,
                        plugin_instance.version,
                        extra_str,
                        folder_name,
                        folder_module_name,
                        f"embeddr_plugins.{plugin_instance.name.replace('-', '_').replace('.', '_')}",
                    )

                # --- API Registration (your existing logic, unchanged) ---
                if app and PluginIntent.REGISTER_API in plugin_instance.intents:
                    if not getattr(plugin_instance, "_api_registered", False):
                        try:
                            from embeddr.api.security import check_auth_enabled, get_api_key

                            api_dependencies = (
                                [Depends(get_api_key)
                                 ] if check_auth_enabled() else []
                            )
                            plugin_router = APIRouter(
                                prefix=f"/api/v1/plugins/{plugin_instance.name}",
                                tags=[plugin_instance.name],
                                dependencies=api_dependencies,
                            )
                            plugin_instance.register_api(plugin_router)
                            app.include_router(plugin_router)
                            plugin_instance._api_registered = True
                            logger.debug(
                                "  -> Registered API for %s at /api/v1/plugins/%s",
                                plugin_instance.name,
                                plugin_instance.name,
                            )
                        except Exception as e:
                            logger.error(
                                "Failed to register API for %s: %s", plugin_instance.name, e)

                # --- CLI Registration (your existing logic, unchanged) ---
                if cli_app and PluginIntent.REGISTER_CLI in plugin_instance.intents:
                    try:
                        plugin_typer = typer.Typer(
                            help=f"Commands for {plugin_instance.name}",
                            no_args_is_help=True,
                        )
                        plugin_instance.register_cli(plugin_typer)
                        cli_app.add_typer(
                            plugin_typer, name=plugin_instance.name)
                        logger.debug(
                            "  -> Registered CLI group '%s'", plugin_instance.name)
                    except Exception as e:
                        logger.error(
                            "Failed to register CLI for %s: %s", plugin_instance.name, e)

                # --- LOTUS registration (your existing logic, unchanged) ---
                try:
                    if hasattr(plugin_instance, "register_lotus"):
                        caps = plugin_instance.register_lotus() or []
                        for cap in caps:
                            if not cap.plugin:
                                cap.plugin = plugin_instance.name
                            if not cap.version:
                                cap.version = plugin_instance.version
                            if cap.plugin and "." not in cap.id and not cap.id.startswith(f"{cap.plugin}."):
                                cap.id = f"{cap.plugin}.{cap.id}"
                            _LOTUS_REGISTRY.register(cap)
                except Exception as e:
                    logger.error(
                        "Failed to register LOTUS capabilities for %s: %s", plugin_instance.name, e)

                return

            # 2) Legacy Function-based Plugin (unchanged)
            if hasattr(module, "register") and app:
                logger.info("Registering legacy plugin: %s", folder_name)
                router = APIRouter(
                    prefix=f"/api/v1/plugins/{folder_name}", tags=[folder_name])
                module.register(router)
                app.include_router(router)

        except Exception as e:
            logger.error("=" * 72)
            logger.error("PLUGIN LOAD FAILURE")
            logger.error("Plugin: %s", folder_name)
            logger.error("Path: %s", str(plugin_file))
            logger.error("Error: %s", e)
            logger.error("=" * 72)
            logger.debug(
                "Plugin load failure details (plugin=%s path=%s)",
                folder_name,
                str(plugin_file),
                exc_info=True,
            )

    # Main scan loop
    for item in plugins_dir.iterdir():
        if item.is_dir():
            # Categories that contain multiple plugins
            categories = [
                "core",
                "integrations",
                "development",
                "private",
                "plugins",
                "private_plugins",
                "storage",
                "types",
            ]
            if item.name in categories:
                # Recurse one level into folders
                if item.exists():
                    for sub in item.iterdir():
                        if sub.is_dir():
                            process_plugin_dir(sub)
            else:
                # Direct plugin directory
                process_plugin_dir(item)


_INITIALIZED = False


def initialize_all_plugins() -> None:
    """
    Phase 1: Discovery & Initialization.
    Trigger on_load for all plugins with the full capability registry available.
    """
    global _INITIALIZED
    if _INITIALIZED:
        logger.debug("Plugins already initialized, skipping.")
        return

    logger.info(
        f"Initializing {len(_LOADED_PLUGINS)} plugins with capability registry...")

    # After discovery and registration, initialize all plugins with the full capability registry
    context = PluginContext(
        bus=_EVENT_BUS,
        capability_registry=_PLUGIN_CAPABILITY_REGISTRY,
        resources=resource_manager
    )

    # Sort plugins to ensure PROVIDE_EMBEDDINGS and other providers load first if possible
    # This is a heuristic until we have a proper dependency graph
    def sort_key(p):
        if PluginIntent.PROVIDE_EMBEDDINGS in p.intents:
            return 0
        return 1

    sorted_plugins = sorted(_LOADED_PLUGINS, key=sort_key)

    for plugin in sorted_plugins:
        try:
            plugin.on_load(context)
        except Exception as e:
            logger.error(f"Failed to initialize plugin {plugin.name}: {e}")

    _INITIALIZED = True

    # Phase 1b: Register Lotus Async Handlers
    _register_lotus_async_handlers()
    try:
        get_lotus_registry().recheck_dependencies()
    except Exception:
        logger.debug("Lotus dependency recheck failed", exc_info=True)


def _register_lotus_async_handlers() -> None:
    """
    Iterate through registered Lotus Capabilities.
    If a capability is an 'action' with 'exec.mode' == 'async',
    automatically register a handler in ExecutionSpine that routes to plugin.execute.
    """
    registry = get_lotus_registry()
    actions = registry.list(kind=LotusKind.action)
    features = registry.list(kind=LotusKind.feature)
    caps = actions + features

    count = 0
    registered: set[str] = set()
    for cap in caps:
        data = cap.data or {}
        action_def = cap.action
        exec_conf = (action_def.exec if action_def else None) or data.get(
            "exec", {})
        # Default to async if not specified? Or check sync=False logic
        mode = exec_conf.get("mode", "async")

        # All Lotus actions must be runnable via ExecutionSpine.
        # We still keep exec.mode for UI/metadata, but always register handlers.
        action_name = action_def.action if action_def else data.get("action")
        job_type = action_def.job_type if action_def else data.get("job_type")
        plugin_name = cap.plugin

        if not action_name or not plugin_name:
            continue

        # Define the handler adapter
        def make_handler(p_name, a_name):
            def lotus_adapter(context):  # Receives JobContext
                plugin = get_plugin_instance(p_name)
                if not plugin:
                    raise ValueError(
                        f"Plugin {p_name} not found for action {a_name}")

                # Ensure event bus is available for UI actions that emit events.
                if not hasattr(context, "bus"):
                    setattr(context, "bus", _EVENT_BUS)
                if not hasattr(context, "config"):
                    setattr(
                        context,
                        "config",
                        resolve_plugin_config_for_plugin(plugin_name=p_name),
                    )
                if not hasattr(context, "lotus"):
                    setattr(
                        context,
                        "lotus",
                        LotusContext(context=context),
                    )

                # Pass context as the 4th arg.
                # We rely on plugin.execute handling DuckTyped context (inputs, log, etc)
                return plugin.execute(a_name, context.execution_id, context.inputs, context=context)
            return lotus_adapter

        # Register action name + job_type (if provided)
        for handler_key in {action_name, job_type}:
            if not handler_key or handler_key in registered:
                continue
            if handler_key in ExecutionSpine._handlers:
                logger.debug(
                    "Skipping Lotus handler for %s (already registered)",
                    handler_key,
                )
                registered.add(handler_key)
                continue
            ExecutionSpine.register_handler(
                handler_key, make_handler(plugin_name, action_name))
            registered.add(handler_key)
            count += 1
            logger.info(
                "Registered Lotus action handler for %s.%s (mode=%s, job_type=%s)",
                plugin_name,
                action_name,
                mode,
                handler_key,
            )

    if count > 0:
        logger.info(
            f"Registered {count} async handlers from Lotus capabilities.")


def startup_all_plugins() -> None:
    """
    Phase 2: System Start.
    Triggers on_startup hooks after DB and other core services are ready.
    """
    logger.info("Triggering on_startup for all plugins...")
    _reconcile_artifact_types()
    context = PluginContext(
        bus=_EVENT_BUS,
        capability_registry=_PLUGIN_CAPABILITY_REGISTRY,
        resources=resource_manager
    )

    # Sort plugins to ensure PROVIDE_EMBEDDINGS and other providers load first if possible
    def sort_key(p):
        if PluginIntent.PROVIDE_EMBEDDINGS in p.intents:
            return 0
        return 1

    sorted_plugins = sorted(_LOADED_PLUGINS, key=sort_key)

    for plugin in sorted_plugins:
        try:
            if hasattr(plugin, 'on_startup'):
                result = plugin.on_startup(context)
                if inspect.iscoroutine(result):
                    try:
                        loop = asyncio.get_running_loop()
                        loop.create_task(result)
                    except RuntimeError:
                        asyncio.run(result)
        except Exception as e:
            logger.error(f"Failed to startup plugin {plugin.name}: {e}")


def _emit_schema_event(event_type: str, payload: Dict[str, Any]) -> None:
    try:
        _EVENT_BUS.emit(event_type, payload, source="schema")
    except Exception:
        logger.debug("Schema event emit failed", exc_info=True)


def _extract_artifact_type_specs() -> List[Dict[str, Any]]:
    specs: List[Dict[str, Any]] = []
    reg = get_lotus_registry()
    for cap in reg.list(kind=LotusKind.artifact_type):
        data = cap.data or {}
        raw = data.get("types") or data.get("artifact_types") or []
        if isinstance(raw, dict):
            raw = [raw]
        if not isinstance(raw, list):
            continue
        for item in raw:
            if isinstance(item, dict):
                specs.append({"spec": item, "plugin": cap.plugin})
    return specs


def _reconcile_artifact_types() -> None:
    items = _extract_artifact_type_specs()
    if not items:
        return

    pending: List[Dict[str, Any]] = []
    for entry in items:
        try:
            spec = ArtifactTypeSpec.model_validate(entry["spec"])
            pending.append({"spec": spec, "plugin": entry.get("plugin")})
        except Exception as e:
            logger.warning("Invalid artifact type spec: %s", e)

    if not pending:
        return

    with Session(get_engine()) as session:
        created: set[str] = set()
        for _ in range(len(pending) + 1):
            next_pending: List[Dict[str, Any]] = []
            progress = False

            for entry in pending:
                spec: ArtifactTypeSpec = entry["spec"]
                plugin = entry.get("plugin")

                if spec.parent_name:
                    parent = session.get(ArtifactType, spec.parent_name)
                    if not parent and spec.parent_name not in created:
                        next_pending.append(entry)
                        continue

                existing = session.get(ArtifactType, spec.name)
                if existing:
                    if spec.parent_name and existing.parent_name != spec.parent_name:
                        _emit_schema_event(
                            "schema.artifact_type.conflict",
                            {
                                "name": spec.name,
                                "plugin": plugin,
                                "existing_parent": existing.parent_name,
                                "declared_parent": spec.parent_name,
                            },
                        )
                    else:
                        _emit_schema_event(
                            "schema.artifact_type.exists",
                            {"name": spec.name, "plugin": plugin},
                        )
                    continue

                session.add(ArtifactType(**spec.model_dump()))
                created.add(spec.name)
                progress = True
                _emit_schema_event(
                    "schema.artifact_type.created",
                    {"name": spec.name, "plugin": plugin},
                )

            session.commit()

            if not next_pending or not progress:
                pending = next_pending
                break
            pending = next_pending

        for entry in pending:
            spec: ArtifactTypeSpec = entry["spec"]
            _emit_schema_event(
                "schema.artifact_type.skipped",
                {"name": spec.name, "reason": "missing_parent"},
            )
