import importlib.util
import logging
import sys
import types
import inspect
from pathlib import Path
from typing import Optional, Any, List, Dict
from fastapi import FastAPI, APIRouter
from embeddr_core.plugin_interface import EmbeddrPlugin, PluginIntent, PluginContext
from embeddr_core.services.resource_manager import resource_manager
from embeddr.core.event_bus import SimpleEventBus, _EVENT_BUS

logger = logging.getLogger(__name__)

# Ensure virtual package for plugins exists
if "embeddr_plugins" not in sys.modules:
    plugin_pkg = types.ModuleType("embeddr_plugins")
    plugin_pkg.__path__ = []
    sys.modules["embeddr_plugins"] = plugin_pkg

# Registry of loaded plugins
_LOADED_PLUGINS: List[EmbeddrPlugin] = []
# _EVENT_BUS is imported from event_bus.py (singleton)

# Capability registry: maps PluginIntent to list of plugin instances
_PLUGIN_CAPABILITY_REGISTRY: Dict[PluginIntent, list] = {}


def get_plugins_by_intent(intent: PluginIntent) -> List[EmbeddrPlugin]:
    """
    Return all loaded plugins that provide the given intent/capability.
    """
    return _PLUGIN_CAPABILITY_REGISTRY.get(intent, [])


def register_plugin_capabilities(plugin: EmbeddrPlugin):
    """
    Register plugin's capabilities (intents) in the global registry.
    """
    for intent in plugin.intents:
        if intent not in _PLUGIN_CAPABILITY_REGISTRY:
            _PLUGIN_CAPABILITY_REGISTRY[intent] = []
        _PLUGIN_CAPABILITY_REGISTRY[intent].append(plugin)


def get_loaded_plugins() -> List[Dict[str, Any]]:
    plugins = []
    for p in _LOADED_PLUGINS:
        # Construct the frontend JS URL assuming standard build output.
        # Server mounts /plugins -> plugins directory.
        # Frontend expects 'url' field.

        plugin_data = {
            "id": p.name,  # Frontend typically uses 'id'
            "name": p.name,
            "version": p.version,
            "intents": [i.value for i in p.intents],
            "actions": [a.model_dump() for a in p.actions],
            "frontend_components": [c.model_dump() for c in getattr(p, 'frontend_components', [])],
            "frontend_actions": [a.model_dump() for a in getattr(p, "frontend_actions", [])],
        }

        # Only add URL if the plugin actually has a dist (frontend build)
        source_path = getattr(p, '_source_path', None)
        if source_path and (source_path / "dist").exists():
            # Point to the UMD bundle generated by embeddr-sdk
            # We mount static assets at /api/v2/plugins/{name}/static
            plugin_data["url"] = f"/api/v2/plugins/{p.name}/static/dist/{p.name}.umd.js"

        plugins.append(plugin_data)
    return plugins


def get_all_plugin_instances() -> List[EmbeddrPlugin]:
    return _LOADED_PLUGINS


def get_plugin_instance(name: str) -> Optional[EmbeddrPlugin]:
    for p in _LOADED_PLUGINS:
        if p.name == name:
            return p
    return None


def load_python_plugins(plugins_dir: Path, app: Optional[FastAPI] = None, cli_app: Any = None) -> None:
    """
    Scans the plugins directory for subdirectories containing a 'plugin.py' file.
    If found, it attempts to load the module and register it.
    Also recurses into specific folders like 'examples' and 'private_plugins'.
    """
    if not plugins_dir.exists():
        return

    logger.debug(f"Scanning for Python plugins in {plugins_dir}...")
    import typer

    def process_plugin_dir(p_dir: Path):
        plugin_file = p_dir / "plugin.py"
        if not plugin_file.exists():
            return

        plugin_name = p_dir.name
        # logger.info(f"Found Python plugin: {plugin_name}")

        try:
            # Sanitize plugin name for module identifier (hyphens are invalid in import statements)
            safe_name = plugin_name.replace("-", "_").replace(".", "_")
            full_module_name = f"embeddr_plugins.{safe_name}"

            # Ensure parent package is in sys.modules so relative imports work
            if "embeddr_plugins" not in sys.modules:
                pkg = types.ModuleType("embeddr_plugins")
                pkg.__path__ = []
                sys.modules["embeddr_plugins"] = pkg

            # Load the module as a package (using submodule_search_locations)
            spec = importlib.util.spec_from_file_location(
                full_module_name,
                plugin_file,
                submodule_search_locations=[str(p_dir)]
            )
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                # Ensure it's recognized as a package for 'from . import sibling'
                module.__path__ = [str(p_dir)]
                module.__package__ = full_module_name
                sys.modules[full_module_name] = module
                spec.loader.exec_module(module)

                # 1. Class-based Plugin (New System)
                plugin_instance = None
                for name, obj in inspect.getmembers(module):
                    if inspect.isclass(obj) and issubclass(obj, EmbeddrPlugin) and obj is not EmbeddrPlugin:
                        # Instantiate
                        plugin_instance = obj()
                        break

                if plugin_instance:
                    # Check if already loaded
                    existing_plugin = next(
                        (p for p in _LOADED_PLUGINS if p.name == plugin_instance.name), None)

                    if existing_plugin:
                        # Use existing instance instead of new one
                        plugin_instance = existing_plugin
                        is_new_load = False
                    else:
                        _LOADED_PLUGINS.append(plugin_instance)
                        # Register plugin's capabilities (intents)
                        register_plugin_capabilities(plugin_instance)
                        is_new_load = True

                    # Store source path for static file mounting
                    # Prefer paths that have 'dist' folder (compiled frontend) which is critical for static assets.
                    # If we load from source (no dist) AFTER loading from dist-plugins (with dist), we must NOT overwrite _source_path.
                    new_has_dist = (p_dir / "dist").exists()
                    current_path = getattr(
                        plugin_instance, '_source_path', None)
                    current_has_dist = (
                        current_path / "dist").exists() if current_path and isinstance(current_path, Path) else False

                    if not current_path:
                        # First time loading
                        plugin_instance._source_path = p_dir
                    elif new_has_dist:
                        # New path has dist, always prefer it (even if current has it, assume later is better/newer)
                        plugin_instance._source_path = p_dir
                    elif not current_has_dist:
                        # neither has dist, just update
                        plugin_instance._source_path = p_dir
                    # Else: current has dist, new does not. KEEP current.

                    # Determine icons for logging (only if new load)
                    if is_new_load:
                        icons = ["🐍"]  # Python loaded
                        extras = []

                        if any(a.ui_component for a in getattr(plugin_instance, 'actions', [])):
                            icons.append("⚛️")
                            extras.append("UI")

                        if PluginIntent.ZEN_PANEL in plugin_instance.intents:
                            icons.append("🧘")
                            extras.append("Zen")

                        if PluginIntent.REGISTER_API in plugin_instance.intents:
                            icons.append("🔌")
                            extras.append("API")

                        if PluginIntent.REGISTER_CLI in plugin_instance.intents:
                            icons.append("💻")
                            extras.append("CLI")

                        icon_str = " ".join(icons)
                        extra_str = f"({', '.join(extras)})" if extras else ""

                        logger.info(
                            f"Loaded Plugin: {icon_str}  {plugin_instance.name} v{plugin_instance.version} {extra_str}")

                    # API Registration (Namespaced) - ALWAYS try if app is present
                    # even if plugin was already loaded previously (e.g. by CLI loader)
                    if app and PluginIntent.REGISTER_API in plugin_instance.intents:
                        # Simple check to avoid double registration: check if we already logged it?
                        # Or perhaps attributes.. For now, simplistic approach:
                        # If we assume create_app is called once, we safe.
                        # However, reloading might be tricky.
                        # Use an attribute on the plugin instance to track registration
                        if not getattr(plugin_instance, "_api_registered", False):
                            try:
                                # Create a router for this plugin
                                plugin_router = APIRouter(
                                    prefix=f"/api/v2/plugins/{plugin_instance.name}",
                                    tags=[plugin_instance.name]
                                )
                                # Pass it to the plugin to fill
                                plugin_instance.register_api(plugin_router)
                                # Mount it to the main app
                                app.include_router(plugin_router)

                                # Mark as registered
                                plugin_instance._api_registered = True

                                logger.debug(
                                    f"  -> Registered API for {plugin_instance.name} at /api/v2/plugins/{plugin_instance.name}")
                            except Exception as e:
                                logger.error(
                                    f"Failed to register API for {plugin_instance.name}: {e}")

                    # CLI Registration (Namespaced)
                    if cli_app and PluginIntent.REGISTER_CLI in plugin_instance.intents:
                        try:
                            # Create a sub-typer for this plugin
                            plugin_typer = typer.Typer(
                                help=f"Commands for {plugin_instance.name}",
                                no_args_is_help=True
                            )
                            # Pass it to the plugin to fill
                            plugin_instance.register_cli(plugin_typer)
                            # Mount it to the main CLI with the plugin name
                            cli_app.add_typer(
                                plugin_typer, name=plugin_instance.name)

                            logger.debug(
                                f"  -> Registered CLI group '{plugin_instance.name}'")
                        except Exception as e:
                            logger.error(
                                f"Failed to register CLI for {plugin_instance.name}: {e}")
                    return

                # 2. Legacy Function-based Plugin
                if hasattr(module, "register") and app:
                    logger.info(f"Registering legacy plugin: {plugin_name}")
                    router = APIRouter(
                        prefix=f"/api/v2/plugins/{plugin_name}", tags=[plugin_name]
                    )
                    module.register(router)
                    app.include_router(router)
        except Exception as e:
            logger.error(
                f"Failed to load plugin {plugin_name} from {plugin_file}: {e}")

    # Main scan loop
    for item in plugins_dir.iterdir():
        if item.is_dir():
            # Categories that contain multiple plugins
            categories = ["core", "development", "examples",
                          "private", "plugins", "private_plugins"]
            if item.name in categories:
                # Recurse one level into folders
                if item.exists():
                    for sub in item.iterdir():
                        if sub.is_dir():
                            process_plugin_dir(sub)
            else:
                # Direct plugin directory
                process_plugin_dir(item)


_INITIALIZED = False


def initialize_all_plugins() -> None:
    """
    Phase 1: Discovery & Initialization.
    Trigger on_load for all plugins with the full capability registry available.
    """
    global _INITIALIZED
    if _INITIALIZED:
        logger.debug("Plugins already initialized, skipping.")
        return

    logger.info(
        f"Initializing {len(_LOADED_PLUGINS)} plugins with capability registry...")

    # After discovery and registration, initialize all plugins with the full capability registry
    context = PluginContext(
        bus=_EVENT_BUS,
        capability_registry=_PLUGIN_CAPABILITY_REGISTRY,
        resources=resource_manager
    )

    # Sort plugins to ensure PROVIDE_EMBEDDINGS and other providers load first if possible
    # This is a heuristic until we have a proper dependency graph
    def sort_key(p):
        if PluginIntent.PROVIDE_EMBEDDINGS in p.intents:
            return 0
        return 1

    sorted_plugins = sorted(_LOADED_PLUGINS, key=sort_key)

    for plugin in sorted_plugins:
        try:
            plugin.on_load(context)
        except Exception as e:
            logger.error(f"Failed to initialize plugin {plugin.name}: {e}")

    _INITIALIZED = True


def startup_all_plugins() -> None:
    """
    Phase 2: System Start.
    Triggers on_startup hooks after DB and other core services are ready.
    """
    logger.info("Triggering on_startup for all plugins...")
    context = PluginContext(
        bus=_EVENT_BUS,
        capability_registry=_PLUGIN_CAPABILITY_REGISTRY,
        resources=resource_manager
    )

    # Sort plugins to ensure PROVIDE_EMBEDDINGS and other providers load first if possible
    def sort_key(p):
        if PluginIntent.PROVIDE_EMBEDDINGS in p.intents:
            return 0
        return 1

    sorted_plugins = sorted(_LOADED_PLUGINS, key=sort_key)

    for plugin in sorted_plugins:
        try:
            if hasattr(plugin, 'on_startup'):
                plugin.on_startup(context)
        except Exception as e:
            logger.error(f"Failed to startup plugin {plugin.name}: {e}")
