"""Add Automation Table

Revision ID: 06d97c8c83e8
Revises: b8c5529c95fa
Create Date: 2026-01-12 22:12:10.446248

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d97c8c83e8'
down_revision: Union[str, Sequence[str], None] = 'b8c5529c95fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('trigger_event',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('trigger_conditions', sa.JSON(), nullable=False),
                    sa.Column('actions', sa.JSON(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_name'), [
                              'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_trigger_event'), [
                              'trigger_event'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_trigger_event'))
        batch_op.drop_index(batch_op.f('ix_automation_name'))

    op.drop_table('automation')
    # ### end Alembic commands ###
