"""Add auto analysis config

Revision ID: 08418dcb87ca
Revises: 25f45aa3495d
Create Date: 2026-01-11 19:13:58.766662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08418dcb87ca'
down_revision: Union[str, Sequence[str], None] = '25f45aa3495d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if table 'autoanalysisconfig' already exists before creating
    # This check is manual because op.create_table does not support IF NOT EXISTS on all backends
    # and we want to avoid crashing on partial migrations.

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'autoanalysisconfig' not in tables:
        op.create_table('autoanalysisconfig',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column(
                            'scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                        sa.Column('scope_id', sa.Uuid(), nullable=True),
                        sa.Column('plugin_name', sqlmodel.sql.sqltypes.AutoString(),
                                  nullable=False),
                        sa.Column('enabled', sa.Boolean(), nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('scope', 'scope_id', 'plugin_name',
                                            name='unique_analysis_config')
                        )
        with op.batch_alter_table('autoanalysisconfig', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_autoanalysisconfig_plugin_name'), [
                                  'plugin_name'], unique=False)
            batch_op.create_index(batch_op.f('ix_autoanalysisconfig_scope'), [
                                  'scope'], unique=False)
            batch_op.create_index(batch_op.f('ix_autoanalysisconfig_scope_id'), [
                                  'scope_id'], unique=False)

    if 'dataset' not in tables:
        op.create_table('dataset',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column(
                            'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                                  nullable=True),
                        sa.Column('type', sa.Enum('REGULAR', 'IMAGE_PAIR',
                                                  name='datasettype'), nullable=False),
                        sa.Column('collection_id',
                                  sa.Integer(), nullable=True),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.Column('captioning_config',
                                  sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        with op.batch_alter_table('dataset', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_dataset_collection_id'), [
                                  'collection_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_dataset_name'), [
                                  'name'], unique=False)

    if 'datasetitem' not in tables:
        op.create_table('datasetitem',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('dataset_id', sa.Integer(), nullable=False),
                        sa.Column('original_image_id',
                                  sa.Integer(), nullable=False),
                        sa.Column('processed_image_path',
                                  sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                        sa.Column('pair_image_path',
                                  sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                        sa.Column(
                            'caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                        sa.ForeignKeyConstraint(
                            ['dataset_id'], ['dataset.id'], ),
                        sa.ForeignKeyConstraint(
                            ['original_image_id'], ['localimage.id'], ),
                        sa.PrimaryKeyConstraint('id')
                        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasetitem')
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_name'))
        batch_op.drop_index(batch_op.f('ix_dataset_collection_id'))

    op.drop_table('dataset')
    with op.batch_alter_table('autoanalysisconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autoanalysisconfig_scope_id'))
        batch_op.drop_index(batch_op.f('ix_autoanalysisconfig_scope'))
        batch_op.drop_index(batch_op.f('ix_autoanalysisconfig_plugin_name'))

    op.drop_table('autoanalysisconfig')
    # ### end Alembic commands ###
