"""Add ArtifactPreview

Revision ID: 234efd3b3f19
Revises: 344367c39e1c
Create Date: 2026-01-09 02:18:01.780955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234efd3b3f19'
down_revision: Union[str, Sequence[str], None] = '5a1f6b7c8d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifactpreview',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('artifact_id', sa.Uuid(), nullable=False),
                    sa.Column('preview_type', sa.String(), nullable=False),
                    sa.Column('mime_type', sa.String(), nullable=False),
                    sa.Column('uri', sa.String(), nullable=False),
                    sa.Column('width', sa.Integer(), nullable=True),
                    sa.Column('height', sa.Integer(), nullable=True),
                    sa.Column('plugin_name', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artifact_id'], ['artifact.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('artifactpreview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifactpreview_artifact_id'), [
                              'artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactpreview_plugin_name'), [
                              'plugin_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactpreview_preview_type'), [
                              'preview_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifactpreview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifactpreview_preview_type'))
        batch_op.drop_index(batch_op.f('ix_artifactpreview_plugin_name'))
        batch_op.drop_index(batch_op.f('ix_artifactpreview_artifact_id'))

    op.drop_table('artifactpreview')
    # ### end Alembic commands ###
