"""add pluginconfig

Revision ID: 2434604c8120
Revises: 06d97c8c83e8
Create Date: 2026-01-18 02:21:36.018524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2434604c8120'
down_revision: Union[str, Sequence[str], None] = '06d97c8c83e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pluginconfig',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'plugin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('value', sa.JSON(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('pluginconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pluginconfig_plugin_name'), [
                              'plugin_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pluginconfig_scope'), [
                              'scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_pluginconfig_scope_id'), [
                              'scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pluginconfig_updated_at'), [
                              'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pluginconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pluginconfig_updated_at'))
        batch_op.drop_index(batch_op.f('ix_pluginconfig_scope_id'))
        batch_op.drop_index(batch_op.f('ix_pluginconfig_scope'))
        batch_op.drop_index(batch_op.f('ix_pluginconfig_plugin_name'))

    op.drop_table('pluginconfig')
    # ### end Alembic commands ###
