"""Add ArtifactExecution

Revision ID: 25f45aa3495d
Revises: 234efd3b3f19
Create Date: 2026-01-09 03:09:36.313017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25f45aa3495d'
down_revision: Union[str, Sequence[str], None] = '234efd3b3f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifactexecution',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'plugin_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('action_name', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('inputs', sa.JSON(), nullable=False),
                    sa.Column('outputs', sa.JSON(), nullable=True),
                    sa.Column('primary_artifact_id', sa.Uuid(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.Column('finished_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['primary_artifact_id'], ['artifact.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('artifactexecution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifactexecution_action_name'), [
                              'action_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactexecution_plugin_name'), [
                              'plugin_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactexecution_primary_artifact_id'), [
                              'primary_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactexecution_status'), [
                              'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactexecution_tier'), [
                              'tier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifactexecution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifactexecution_tier'))
        batch_op.drop_index(batch_op.f('ix_artifactexecution_status'))
        batch_op.drop_index(batch_op.f(
            'ix_artifactexecution_primary_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_artifactexecution_plugin_name'))
        batch_op.drop_index(batch_op.f('ix_artifactexecution_action_name'))

    op.drop_table('artifactexecution')
    # ### end Alembic commands ###
