"""make collection_id optional

Revision ID: 344367c39e1c
Revises: 74473b8347c3
Create Date: 2026-01-05 20:56:32.250671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344367c39e1c'
down_revision: Union[str, Sequence[str], None] = '74473b8347c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
