"""add parent execution id

Revision ID: 7da09e23a056
Revises: 95323a42b283
Create Date: 2026-01-19 11:00:01.852942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7da09e23a056'
down_revision: Union[str, Sequence[str], None] = '95323a42b283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifactexecution', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('parent_execution_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_artifactexecution_parent_execution_id'), [
                              'parent_execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifactexecution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(
            'ix_artifactexecution_parent_execution_id'))
        batch_op.drop_column('parent_execution_id')

    # ### end Alembic commands ###
