"""Add priority to config

Revision ID: 840ce9d7b56d
Revises: 08418dcb87ca
Create Date: 2026-01-11 20:37:41.625784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840ce9d7b56d'
down_revision: Union[str, Sequence[str], None] = '08418dcb87ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autoanalysisconfig', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autoanalysisconfig', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
