"""add artifactingest

Revision ID: 95323a42b283
Revises: 2434604c8120
Create Date: 2026-01-18 07:46:41.931392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95323a42b283'
down_revision: Union[str, Sequence[str], None] = '2434604c8120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '5a1f6b7c8d9e'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifactblob',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('artifact_id', sa.Uuid(), nullable=False),
                    sa.Column('storage_backend', sa.String(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('sha256', sa.String(), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column('content_type', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artifact_id'], ['artifact.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('artifactblob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifactblob_artifact_id'), [
                              'artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactblob_storage_backend'), [
                              'storage_backend'], unique=False)

    op.create_table('artifactingest',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('artifact_id', sa.Uuid(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('storage_backend', sa.String(), nullable=False),
                    sa.Column('storage_path', sa.String(), nullable=True),
                    sa.Column('content_type', sa.String(), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column('original_filename', sa.String(), nullable=True),
                    sa.Column('meta_json', sa.JSON(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artifact_id'], ['artifact.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('artifactingest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifactingest_artifact_id'), [
                              'artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactingest_status'), [
                              'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactingest_storage_backend'), [
                              'storage_backend'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifactingest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifactingest_storage_backend'))
        batch_op.drop_index(batch_op.f('ix_artifactingest_status'))
        batch_op.drop_index(batch_op.f('ix_artifactingest_artifact_id'))

    op.drop_table('artifactingest')
    with op.batch_alter_table('artifactblob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifactblob_storage_backend'))
        batch_op.drop_index(batch_op.f('ix_artifactblob_artifact_id'))

    op.drop_table('artifactblob')
    # ### end Alembic commands ###
