"""enrich artifact_relation and add relation_type_def table

Revision ID: b1c2d3e4f5a6
Revises: 9d4f2b6c7a8e
Create Date: 2026-03-09 00:00:00.000000

Changes:
  - artifactrelation: add surrogate UUID primary key `id`, drop composite PK
  - artifactrelation: add created_at, weight, metadata_json columns
  - artifactrelation: add unique constraint on (source_id, target_id, relation_type, source_namespace)
  - relationtypedef: new table for plugin-registered relation type semantics
  - Seed core built-in relation types into relationtypedef
"""

from typing import Sequence, Union
import json
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

revision: str = "b1c2d3e4f5a6"
down_revision: Union[str, Sequence[str], None] = "9d4f2b6c7a8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Core built-in relation types to seed into the registry
_CORE_RELATION_TYPES = [
    {
        "name": "contains",
        "family": "containment",
        "inverse": "contained_in",
        "transitive": True,
        "structural": True,
        "description": "Parent artifact contains a child artifact.",
        "registered_by": "core",
    },
    {
        "name": "contained_in",
        "family": "containment",
        "inverse": "contains",
        "transitive": False,
        "structural": True,
        "description": "Artifact is contained within a parent artifact.",
        "registered_by": "core",
    },
    {
        "name": "group",
        "family": "containment",
        "inverse": "member_of",
        "transitive": True,
        "structural": True,
        "description": "Artifact groups one or more member artifacts.",
        "registered_by": "core",
    },
    {
        "name": "member_of",
        "family": "containment",
        "inverse": "group",
        "transitive": False,
        "structural": True,
        "description": "Artifact is a member of a group artifact.",
        "registered_by": "core",
    },
    {
        "name": "part_of",
        "family": "semantic",
        "inverse": None,
        "transitive": False,
        "structural": False,
        "description": "Artifact is a semantic part of another artifact.",
        "registered_by": "core",
    },
    {
        "name": "reference",
        "family": "semantic",
        "inverse": None,
        "transitive": False,
        "structural": False,
        "description": "Artifact references another artifact.",
        "registered_by": "core",
    },
    {
        "name": "generates",
        "family": "workflow",
        "inverse": "generated_by",
        "transitive": False,
        "structural": False,
        "description": "Artifact generates another artifact (workflow output).",
        "registered_by": "core",
    },
    {
        "name": "generated_by",
        "family": "workflow",
        "inverse": "generates",
        "transitive": False,
        "structural": False,
        "description": "Artifact was generated by another artifact.",
        "registered_by": "core",
    },
]


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    existing_tables = inspector.get_table_names()

    # ------------------------------------------------------------------
    # 1. Recreate artifactrelation with enriched schema
    #    SQLite requires batch mode (table recreation) to change PK.
    # ------------------------------------------------------------------
    if "artifactrelation" in existing_tables:
        # Read existing rows before recreation
        existing_rows = conn.execute(
            sa.text("SELECT source_id, target_id, relation_type, source_namespace FROM artifactrelation")
        ).fetchall()

        with op.batch_alter_table("artifactrelation", recreate="always") as batch_op:
            # Drop old composite PK columns and recreate the table.
            # batch_alter_table with recreate="always" drops and rebuilds the table.
            # We define the new schema via the column declarations below.
            pass

        # Drop the table outright and recreate with new schema
        op.drop_table("artifactrelation")

        op.create_table(
            "artifactrelation",
            sa.Column("id", sa.String(36), primary_key=True, nullable=False),
            sa.Column("source_id", sa.String(36), sa.ForeignKey("artifact.id"), nullable=False, index=True),
            sa.Column("target_id", sa.String(36), sa.ForeignKey("artifact.id"), nullable=False, index=True),
            sa.Column("relation_type", sa.String(), nullable=False, index=True),
            sa.Column("source_namespace", sa.String(), nullable=False, server_default="user", index=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                      server_default=sa.func.current_timestamp()),
            sa.Column("weight", sa.Float(), nullable=True),
            sa.Column("metadata_json", sa.JSON(), nullable=False, server_default="{}"),
            sa.UniqueConstraint(
                "source_id", "target_id", "relation_type", "source_namespace",
                name="uq_artifactrelation_edge",
            ),
        )

        op.create_index(
            "ix_artifactrelation_relation_type_ns",
            "artifactrelation",
            ["relation_type", "source_namespace"],
        )

        # Re-insert existing rows with generated UUIDs, deduplicating on the new unique key
        seen_edges: set = set()
        for row in existing_rows:
            source_id, target_id, relation_type, source_namespace = row
            source_namespace = source_namespace or "user"
            relation_type = relation_type or "reference"
            edge_key = (source_id, target_id, relation_type, source_namespace)
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)
            conn.execute(
                sa.text(
                    "INSERT INTO artifactrelation "
                    "(id, source_id, target_id, relation_type, source_namespace, metadata_json) "
                    "VALUES (:id, :source_id, :target_id, :relation_type, :source_namespace, :metadata_json)"
                ),
                {
                    "id": str(uuid4()),
                    "source_id": str(source_id),
                    "target_id": str(target_id),
                    "relation_type": str(relation_type),
                    "source_namespace": str(source_namespace),
                    "metadata_json": "{}",
                },
            )

    # ------------------------------------------------------------------
    # 2. Create relationtypedef table
    # ------------------------------------------------------------------
    if "relationtypedef" not in existing_tables:
        op.create_table(
            "relationtypedef",
            sa.Column("name", sa.String(), primary_key=True, nullable=False),
            sa.Column("family", sa.String(), nullable=False, server_default="other", index=True),
            sa.Column("inverse", sa.String(), nullable=True),
            sa.Column("transitive", sa.Boolean(), nullable=False, server_default="0"),
            sa.Column("structural", sa.Boolean(), nullable=False, server_default="0"),
            sa.Column("description", sa.String(), nullable=False, server_default=""),
            sa.Column("registered_by", sa.String(), nullable=False, server_default="core", index=True),
        )

        # Seed core built-in types
        for rtype in _CORE_RELATION_TYPES:
            conn.execute(
                sa.text(
                    "INSERT INTO relationtypedef "
                    "(name, family, inverse, transitive, structural, description, registered_by) "
                    "VALUES (:name, :family, :inverse, :transitive, :structural, :description, :registered_by)"
                ),
                {
                    "name": rtype["name"],
                    "family": rtype["family"],
                    "inverse": rtype["inverse"],
                    "transitive": 1 if rtype["transitive"] else 0,
                    "structural": 1 if rtype["structural"] else 0,
                    "description": rtype["description"],
                    "registered_by": rtype["registered_by"],
                },
            )


def downgrade() -> None:
    # Restore artifactrelation to its original composite-PK form.
    # Data will be preserved but id/created_at/weight/metadata_json columns are lost.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if "relationtypedef" in existing_tables:
        op.drop_table("relationtypedef")

    if "artifactrelation" in existing_tables:
        existing_rows = conn.execute(
            sa.text("SELECT source_id, target_id, relation_type, source_namespace FROM artifactrelation")
        ).fetchall()

        op.drop_table("artifactrelation")

        op.create_table(
            "artifactrelation",
            sa.Column("source_id", sa.String(36), sa.ForeignKey("artifact.id"),
                      primary_key=True, nullable=False, index=True),
            sa.Column("target_id", sa.String(36), sa.ForeignKey("artifact.id"),
                      primary_key=True, nullable=False, index=True),
            sa.Column("relation_type", sa.String(), nullable=False, index=True),
            sa.Column("source_namespace", sa.String(), nullable=True, server_default="user", index=True),
        )

        seen: set = set()
        for row in existing_rows:
            source_id, target_id, relation_type, source_namespace = row
            key = (source_id, target_id)
            if key in seen:
                continue
            seen.add(key)
            conn.execute(
                sa.text(
                    "INSERT INTO artifactrelation (source_id, target_id, relation_type, source_namespace) "
                    "VALUES (:source_id, :target_id, :relation_type, :source_namespace)"
                ),
                {
                    "source_id": str(source_id),
                    "target_id": str(target_id),
                    "relation_type": str(relation_type or "reference"),
                    "source_namespace": str(source_namespace or "user"),
                },
            )
