"""update_artifactexecution_schema_v2

Revision ID: b8c5529c95fa
Revises: 840ce9d7b56d
Create Date: 2026-01-12 20:34:53.726197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8c5529c95fa'
down_revision: Union[str, Sequence[str], None] = '840ce9d7b56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifactexecution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sqlmodel.sql.sqltypes.AutoString(
        ), nullable=False, server_default='generic'))
        batch_op.add_column(sa.Column('resource_class', sqlmodel.sql.sqltypes.AutoString(
        ), nullable=False, server_default='cpu'))
        batch_op.add_column(
            sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(
            sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column(
            'message', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.drop_index(batch_op.f('ix_artifactexecution_action_name'))
        batch_op.drop_index(batch_op.f('ix_artifactexecution_tier'))
        batch_op.create_index(batch_op.f('ix_artifactexecution_priority'), [
                              'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactexecution_type'), [
                              'type'], unique=False)
        batch_op.drop_column('action_name')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifactexecution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.VARCHAR(), nullable=False))
        batch_op.add_column(
            sa.Column('action_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_artifactexecution_type'))
        batch_op.drop_index(batch_op.f('ix_artifactexecution_priority'))
        batch_op.create_index(batch_op.f('ix_artifactexecution_tier'), [
                              'tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifactexecution_action_name'), [
                              'action_name'], unique=False)
        batch_op.drop_column('message')
        batch_op.drop_column('progress')
        batch_op.drop_column('priority')
        batch_op.drop_column('resource_class')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
